version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
      - "8000:8000"
    expose:
      - 9000
      - 8000
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.frontend.rule=Host(`le-5ra.de`, `www.le-5ra.de`) "
      - "traefik.http.routers.frontend.middlewares=secureHeaders@file"
#      - "traefik.http.routers.frontend.entrypoints=websecure"
#      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
# - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.priority=900"
      - "traefik.http.routers.frontend.tls=true"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.le-5ra.de`)"
      - "traefik.http.routers.edge.middlewares=secureHeaders@file"
#      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
        #     - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=letsencrypt"
      - "traefik.http.routers.edge.priority=800"
      - "traefik.http.routers.edge.tls=true"


volumes:
  portainer_data:

networks:
  default:
    external:
      name: traefik-proxy
